# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }

from genlayer import *
import json


class GenTuring(gl.Contract):
    """
    GenTuring Intelligent Contract

    Purpose:
    - Store completed GenTuring matches.
    - Let a player submit a chat transcript and their guess.
    - Use GenLayer AI reasoning to judge whether the hidden participant was human or AI.
    - Finalise the match result.
    - Track player stats.
    """

    total_games: u64
    correct_guesses: u64

    matches: TreeMap[str, str]
    player_stats: TreeMap[str, str]

    def __init__(self):
        self.total_games = 0
        self.correct_guesses = 0

    @gl.public.view
    def get_global_stats(self) -> dict:
        return {
            "total_games": int(self.total_games),
            "correct_guesses": int(self.correct_guesses)
        }

    @gl.public.view
    def get_match(self, match_id: str) -> str:
        return self.matches.get(match_id, "null")

    @gl.public.view
    def get_player_stats(self, player_key: str) -> str:
        return self.player_stats.get(player_key, "null")

    @gl.public.view
    def match_exists(self, match_id: str) -> bool:
        return match_id in self.matches

    def _build_judge_prompt(self, transcript: str) -> str:
        return (
            "You are the GenTuring judge inside a GenLayer Intelligent Contract.\n"
            "Your task is to analyse a completed chat transcript and decide whether "
            "the hidden participant was most likely a human or an AI.\n\n"

            "Important judging criteria:\n"
            "- natural typos or imperfect phrasing\n"
            "- emotional spontaneity\n"
            "- overly polished or generic language\n"
            "- repetitive phrasing\n"
            "- unnatural helpfulness\n"
            "- refusal patterns\n"
            "- sentence rhythm\n"
            "- context memory across the conversation\n"
            "- whether the responses feel socially natural or model-like\n\n"

            "Do not judge only one line. Judge the full behaviour across the transcript.\n\n"

            f"Transcript:\n{transcript}\n\n"

            "Return ONLY valid JSON.\n"
            "No markdown. No code block. No explanation outside JSON.\n\n"

            "Return exactly this JSON shape:\n"
            "{"
            "\"verdict\":\"human or ai\","
            "\"confidence\":\"low, medium, or high\","
            "\"reason\":\"one short sentence explaining the behavioural signal\""
            "}"
        )

    def _safe_parse_judgement(self, raw: str) -> dict:
        cleaned = str(raw).replace("```json", "").replace("```", "").strip()

        try:
            data = json.loads(cleaned)
        except Exception:
            data = {
                "verdict": "ai",
                "confidence": "low",
                "reason": "The judge returned unreadable output, so the contract used a safe fallback."
            }

        verdict = str(data.get("verdict", "")).lower().strip()
        confidence = str(data.get("confidence", "")).lower().strip()
        reason = str(data.get("reason", "")).replace("\n", " ").strip()

        if verdict not in ["human", "ai"]:
            verdict = "ai"

        if confidence not in ["low", "medium", "high"]:
            confidence = "medium"

        if reason == "":
            reason = "The transcript showed the strongest behavioural signal for the selected verdict."

        if len(reason) > 180:
            reason = reason[:177] + "..."

        return {
            "verdict": verdict,
            "confidence": confidence,
            "reason": reason
        }

    @gl.public.write
    def judge_match(
        self,
        match_id: str,
        player_key: str,
        transcript: str,
        player_guess: str
    ) -> str:
        """
        Frontend calls this after a player finishes a GenTuring round.

        match_id:
        - unique id generated by frontend/backend for the completed match.

        player_key:
        - connected wallet address, user id, or any stable player identifier.

        transcript:
        - full chat transcript between the player and the hidden participant.
        - frontend should send it as plain text or JSON string.

        player_guess:
        - "human" or "ai"
        """

        if match_id in self.matches:
            return self.matches[match_id]

        guess = player_guess.lower().strip()

        if guess != "human" and guess != "ai":
            raise Exception("player_guess must be either 'human' or 'ai'")

        judge_prompt = self._build_judge_prompt(transcript)

        def leader_fn() -> dict:
            raw = gl.nondet.exec_prompt(judge_prompt)
            return self._safe_parse_judgement(str(raw))

        def validator_fn(leader_result) -> bool:
            if not isinstance(leader_result, gl.vm.Return):
                return False

            leader_data = leader_result.calldata
            validator_data = leader_fn()

            if not isinstance(leader_data, dict):
                return False

            leader_verdict = str(leader_data.get("verdict", "")).lower().strip()
            validator_verdict = str(validator_data.get("verdict", "")).lower().strip()

            leader_confidence = str(leader_data.get("confidence", "")).lower().strip()

            return (
                leader_verdict in ["human", "ai"]
                and leader_confidence in ["low", "medium", "high"]
                and leader_verdict == validator_verdict
            )

        judgement = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)

        actual_verdict = str(judgement.get("verdict", "")).lower().strip()
        confidence = str(judgement.get("confidence", "")).lower().strip()
        reason = str(judgement.get("reason", "")).replace("\n", " ").strip()

        if actual_verdict not in ["human", "ai"]:
            actual_verdict = "ai"

        if confidence not in ["low", "medium", "high"]:
            confidence = "medium"

        if reason == "":
            reason = "The transcript showed the strongest behavioural signal for the selected verdict."

        if len(reason) > 180:
            reason = reason[:177] + "..."

        correct = guess == actual_verdict

        existing_stats_raw = self.player_stats.get(player_key, "null")

        if existing_stats_raw == "null":
            player_data = {
                "games_played": 0,
                "correct_guesses": 0
            }
        else:
            try:
                player_data = json.loads(existing_stats_raw)
            except Exception:
                player_data = {
                    "games_played": 0,
                    "correct_guesses": 0
                }

        player_data["games_played"] = int(player_data.get("games_played", 0)) + 1

        if correct:
            player_data["correct_guesses"] = int(player_data.get("correct_guesses", 0)) + 1

        accuracy = 0

        if int(player_data["games_played"]) > 0:
            accuracy = (
                int(player_data["correct_guesses"]) * 100
            ) // int(player_data["games_played"])

        player_data["accuracy"] = accuracy

        final_match = {
            "match_id": match_id,
            "player_key": player_key,
            "player_guess": guess,
            "verdict": actual_verdict,
            "confidence": confidence,
            "reason": reason,
            "correct": correct
        }

        stored_match = json.dumps(final_match, sort_keys=True)
        stored_player = json.dumps(player_data, sort_keys=True)

        self.matches[match_id] = stored_match
        self.player_stats[player_key] = stored_player

        self.total_games += 1

        if correct:
            self.correct_guesses += 1

        return stored_match